/*
 * Generated by Bluespec Compiler, version 2024.07-4-g6f298148 (build 6f298148)
 * 
 * On Sat Oct  5 22:24:02 CST 2024
 * 
 */

/* Generation options: keep-fires */
#ifndef __model_sysServerTestUpdate_h__
#define __model_sysServerTestUpdate_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

#include "bs_model.h"
#include "sysServerTestUpdate.h"

/* Class declaration for a model of sysServerTestUpdate */
class MODEL_sysServerTestUpdate : public Model {
 
 /* Top-level module instance */
 private:
  MOD_sysServerTestUpdate *sysServerTestUpdate_instance;
 
 /* Handle to the simulation kernel */
 private:
  tSimStateHdl sim_hdl;
 
 /* Constructor */
 public:
  MODEL_sysServerTestUpdate();
 
 /* Functions required by the kernel */
 public:
  void create_model(tSimStateHdl simHdl, bool master);
  void destroy_model();
  void reset_model(bool asserted);
  void get_version(char const **name, char const **build);
  time_t get_creation_time();
  void * get_instance();
  void dump_state();
  void dump_VCD_defs();
  void dump_VCD(tVCDDumpType dt);
};

/* Function for creating a new model */
extern "C" {
  void * new_MODEL_sysServerTestUpdate();
}

#endif /* ifndef __model_sysServerTestUpdate_h__ */
